### ISSUE TITLE
Error when using georges_core.kinematics

### ISSUE THREAD

**Issue by eramoisi** [ULB-Metronu/georges-core#4]
---------------------------------------------------------------------------
ZgoubiKinematicsException                 Traceback (most recent call last)
<ipython-input-442-6cb143fbaa32> in <module>
----> 1 georges_core.kinematics.range_to_ekin(4.129*_ureg.cm)

~/reps/georges-core/georges_core/kinematics.py in range_to_ekin(r, particle)
    648     """
    649     if not isinstance(particle, _Proton):
--> 650         raise ZgoubiKinematicsException("Conversion from range only works for protons.")
    651 
    652     a = 0.00169

ZgoubiKinematicsException: Conversion from range only works for protons.

**Comment by chernals** [comment]
@SirEliott   Peux-tu un peu clarifier et notamment mettre un bout de code d'example et formater le tout ?
